language: node_js

node_js:
  - '12'

notifications:
  email:
     recipients:
       - eilgwon88@gmail.com
     on_success: always

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - git lfs pull

install:
  - yarn install

script:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      CI=false yarn build;
      yarn publish
    fi

branches:
  only:
    - master
