language: node_js

node_js:
  - '12'

notifications:
  email:
     recipients:
       - eilgwon@hanmail.net
     on_success: always

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      CI=false yarn build;
      yarn publish
    fi

deploy:
  provider: npm
  email: eilgwon@hanmail.net
  api_key: $NPM_TOKEN

branches:
  only:
    - master
