language: node_js

node_js:
  - '12'

notifications:
  email:
     recipients:
       - eilgwon@hanmail.net
     on_success: always

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

deploy:
  provider: npm
  email: eilgwon@hanmail.net
  api_key: $NPM_TOKEN
  on:
    branches: master

branches:
  only:
    - master
